name: build-ami
on:
  push:
    branches: [main]
    paths:
      - environment/**
      - .github/workflows/build-ami.yml
permissions:
  contents: read
  id-token: write
jobs:
  build-ami:
    environment: aws
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::260760892802:role/cml-terraform-provider
      - run: |
          packer init environment
          packer build environment
