name: build-cml-ami
on: 
  push:
    tags:
      - 'ami*'

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and copy
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          sudo apt install unzip

          cd cml
          packer validate ami.json
          packer build ami.json

