name: Release
on:
  release:
    types: [prereleased]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: |
          printenv TERRAFORM_REGISTRY_GPG_PRIVATE_KEY | gpg --import
        env:
          TERRAFORM_REGISTRY_GPG_PRIVATE_KEY: ${{ secrets.TERRAFORM_REGISTRY_GPG_PRIVATE_KEY }}
      - uses: goreleaser/goreleaser-action@v3
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - run: gh release edit --prerelease=false ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
  synchronize:
    # Empyrically equivalent to pressing the "Resync" button in the Settings
    # page of Terraform Registry, but without bothering humans in the process
    # https://registry.terraform.io/providers/iterative/iterative/latest/settings
    # https://www.terraform.io/docs/registry/providers/publishing.html#webhooks
    needs: release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: hashicorp/setup-terraform@v1
    - run: |
        cat <<END > main.tf
          terraform {
            required_providers {
              iterative = {
                source  = "iterative/iterative",
                version = "${GITHUB_REF##refs/tags/v}"
              }
            }
          }
          provider "iterative" {}
        END
    - run: |
        while ! terraform init; do
          sleep $((2**++try))
        done
