name: Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  schedule:
  - cron: '0 9 * * 1'  # M H d m w (Mondays at 9:00)
jobs:
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v2
        with:
          only-new-issues: true
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - run: make build
    - run: make test
